from extract import *
from transform import *
from load import *
import warnings
warnings.filterwarnings('ignore')


print("Extracting the Data")
csv_keys, json_keys = get_keys()
export_academy(csv_keys)
export_talent(json_keys)
print("Extraction completed")
print("Creating Database")
cursor = cursor_creation()
creation_database(cursor)
create_tables(cursor)
print("Database Created")
print("Transforming the Data")
courses = course_name_table()
trainers = create_trainers_table()
students = table_students()
applicants = applicants_table()
languages = language_table()
tech_scores = tech_score_table()
attributes = get_attributes_table()
junction_2 = junction_table_applicants()
scores = table_scores()
junction_1 = students_applicants_junction_table()
print("Transformation completed!")
print("Populating the Database")
insert_courses(courses,cursor)
insert_trainers(trainers,cursor)
insert_students(students,cursor)
insert_applicants(applicants,cursor)
insert_languages(languages,cursor)
insert_tech_score(tech_scores,cursor)
insert_attributes(attributes,cursor)
insert_junction_table2(junction_2,cursor)
insert_scores(scores,cursor)
insert_junction_table1(junction_1,cursor)
print("Your Database is ready")